const menu = require('./menu')
const command = require('./command')
const position = require('./position')
const contact = require('./contact')
const department = require('./department')
const userContact = require('./userContact')
const logLogin = require('./logLogin')
const logOperate = require('./logOperate')
const errorlog = require('./errorlog')
const mobileModule = require('./mobileModule.js')
const role = require('./role')
const dictionary = require('./dictionary')

module.exports = function (path, app) {
  app.use(path, command)
  app.use(path, menu)
  app.use(path, position)
  app.use(path, contact)
  app.use(path, department)
  app.use(path, userContact)
  app.use(path, logLogin)
  app.use(path, logOperate)
  app.use(path, errorlog)
  app.use(path, mobileModule)
  app.use(path, role)
  app.use(path, dictionary)
}
